language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - gcc-9

before_script:
 - make clean
 - make CXX=g++-9

script: 
 - sh -e ./test/test_all.sh
