language: cpp

#before_install:
# - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
# - sudo apt-get update -qq

#install:
# - sudo apt-get install -qq gcc-4.8 g++-4.8 
# - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5

before_script:
 - make clean
 - make

script: 
 - sh -e ./test/test_all.sh
