#!/bin/bash
# loopserial command
# usage: loopserial <commmand> <args...>
# Multiapply trys the command until the command
# is failed, and outputs the output of the last successful trial.

# version: "Sat Jan 10 16:58:28 JST 2015"

# This command should be rewritten with C/C++.

[ "$#" -lt 1 ] && exit 1

tmp=/tmp/$$
"$@" > $tmp-keep

while [ $? -eq 0 ] ; do
	mv $tmp-keep $tmp-out
	cat $tmp-out | "$@" > $tmp-keep 2> /dev/null
done

cat $tmp-out

rm -f $tmp-*
exit 0
