#!/bin/bash 

tmp=/tmp/$$
dir=$(dirname $0)

OPT=""
[ "${1:0:1}" = "-" ] && OPT="$1" && shift

#dir=$(dirname $0)
SCR="$1"
shift
$dir/langToBash "$SCR" 2> /tmp/error | tee /tmp/hoge > $tmp-scr

if [ "$OPT" = "" ] ;then
	bash $tmp-scr "$@"
else 
	bash "$OPT" $tmp-scr "$@"
fi

rm -f $tmp-*
